[context.production.environment]
  HUGO_VERSION = "0.115.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.115.3"

[[redirects]]
  from = "/docs"
  to = "/docs/v3.3"
  status = 302
  force = true

[[redirects]]
  from = "/zh/docs"
  to = "/zh/docs/v3.3"
  status = 302
  force = true

[[redirects]]
  from = "/docs/*"
  to = "/docs/v3.3/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/zh/docs/*"
  to = "/zh/docs/v3.3/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/log/*"
  to = "https://log.kubesphere.io/:splat"
  status = 308
  force = true

[[redirects]]
  from = "/tr/forum/*"
  to = "http://139.198.113.75:9900/tr/forum/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/forum/*"
  to = "https://ask.kubesphere.io/forum/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/forum/"
  to = "https://ask.kubesphere.io/forum/"
  status = 301
  force = true

[[redirects]]
  from = "/learn/"
  to = "/zh/learn/"
  status = 301
  force = true

[[redirects]]
  from = "/learn/*"
  to = "/zh/learn/*"
  status = 301
  force = true

[[redirects]]
  from = "/live/"
  to = "/zh/live/"
  status = 301
  force = true

[[redirects]]
  from = "/live/*"
  to = "/zh/live/*"
  status = 301
  force = true
