[context.production.environment]
  HUGO_VERSION = "0.105.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.105.0"

[[redirects]]
  from = "/docs"
  to = "/docs/v3.3"
  status = 302
  force = true

[[redirects]]
  from = "/zh/docs"
  to = "/zh/docs/v3.3"
  status = 302
  force = true

[[redirects]]
  from = "/docs/*"
  to = "/docs/v3.3/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/zh/docs/*"
  to = "/zh/docs/v3.3/:splat"
  status = 301
  force = true
