[context.production.environment]
  HUGO_VERSION = "0.101.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.101.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
