[context.production.environment]
  HUGO_VERSION = "0.125.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.0"

[[redirects]]
  from = "/log/*"
  to = "https://log.kubesphere.io/:splat"
  status = 308
  force = true

[[redirects]]
  from = "/tr/forum/*"
  to = "http://139.198.113.75:9900/tr/forum/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/forum/*"
  to = "https://ask.kubesphere.io/forum/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/forum/"
  to = "https://ask.kubesphere.io/forum/"
  status = 301
  force = true

