baseURL = "https://kubesphere.io"

[params]

addGoogleAnalytics = true
addGoogleTag = true
hotjarTracking = true
youtubeLink = "https://www.youtube.com/c/KubeSphere"
addLinkedin = true
addTwitter = true